---
- hosts: localhost
 
  vars:
    resource_group: __resource_group__
    location: __location__
    webapp_name: __webapp_name__
    webapp_plan: __webapp_plan__

  tasks:
    - name: create a resource group
      azure_rm_resourcegroup:
         name: "{{resource_group}}"
         location: "{{location}}"

    - name: create an app service on windows with dotnot core runtime
      azure_rm_webapp:
         resource_group: "{{resource_group}}"
         name: "{{webapp_name}}"
         plan:
           resource_group: "{{resource_group}}"
           name: "{{webapp_plan}}"
           is_linux: false
           sku: S1
...
